# Generated by Django 5.1.7 on 2025-04-26 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=70, verbose_name="Введите заголовок"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Содержимое блога"
                    ),
                ),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="media/blog_previews/",
                        verbose_name="Вставьте Изображение",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "is_publication_attribute",
                    models.BooleanField(
                        default=False, verbose_name="Состояние публикации"
                    ),
                ),
                (
                    "views_counter",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество просмотров"
                    ),
                ),
            ],
            options={
                "verbose_name": "Блоговая запись",
                "verbose_name_plural": "Блоговые записи",
            },
        ),
    ]
