# Generated by Django 5.1.7 on 2025-04-26 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogentry",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Введите дату создания",
                verbose_name="Дата создания",
            ),
        ),
        migrations.AlterField(
            model_name="blogentry",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Введите содержимое блога",
                null=True,
                verbose_name="Содержимое блога",
            ),
        ),
        migrations.AlterField(
            model_name="blogentry",
            name="is_publication_attribute",
            field=models.BooleanField(
                default=False,
                help_text="Определите состояние публикации",
                verbose_name="Состояние публикации",
            ),
        ),
        migrations.AlterField(
            model_name="blogentry",
            name="preview",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите изображение",
                null=True,
                upload_to="blogs/photo/",
                verbose_name="Изображение",
            ),
        ),
        migrations.AlterField(
            model_name="blogentry",
            name="title",
            field=models.CharField(
                help_text="Введите заголовок", max_length=70, verbose_name="Заголовок"
            ),
        ),
        migrations.AlterField(
            model_name="blogentry",
            name="views_counter",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Введите количество просмотров публикации",
                verbose_name="Количество просмотров",
            ),
        ),
    ]
