# Generated by Django 5.1.7 on 2025-04-27 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0003_category_alter_blogentry_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogentry",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="Articles",
                to="blogs.category",
                verbose_name="Категория статьи",
            ),
        ),
    ]
