# Generated by Django 5.1.7 on 2025-05-21 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_product_is_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name", "price", "category"],
                "permissions": [("can_unpublish_product", "Can unpublish product")],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="publish_status",
            field=models.CharField(
                choices=[
                    ("published", "Опубликован"),
                    ("unpublished", "Не опубликован"),
                ],
                default="moderation",
                max_length=20,
                verbose_name="Статус публикации",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(
                default=True, verbose_name="Готовность товара к продаже"
            ),
        ),
    ]
