# Generated by Django 5.1.7 on 2025-06-04 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_product_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=100, verbose_name="URL-идентификатор (slug)"
            ),
        ),
    ]
