# Generated by Django 5.1.7 on 2025-06-04 20:48

from django.db import migrations
from django.utils.text import slugify


def fill_category_slugs(apps, schema_editor):
    Category = apps.get_model('catalog', 'Category')
    for category in Category.objects.all():
        if not category.slug:  # Заполняем только если slug пустой
            category.slug = slugify(category.name)
            category.save()


def reverse_fill(apps, schema_editor):
    """Функция для отката миграции - не обязательна, но рекомендуется"""
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('catalog', '0010_category_slug'),
    ]

    operations = [
        migrations.RunPython(
            fill_category_slugs,
            reverse_fill,
        ),
    ]