# Generated by Django 5.1.7 on 2025-06-04 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0011_fill_category_slugs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                blank=True,
                max_length=100,
                unique=True,
                verbose_name="URL-идентификатор (slug)",
            ),
        ),
    ]
